export class AppError extends Error {
  constructor(
    public code: string,
    message: string,
    public statusCode: number = 400,
    public details?: unknown,
  ) {
    super(message);
    this.name = 'AppError';
  }
}

export const ErrorCodes = {
  INVALID_FIGMA_URL: 'INVALID_FIGMA_URL',
  FIGMA_TOKEN_INVALID: 'FIGMA_TOKEN_INVALID',
  FIGMA_ACCESS_DENIED: 'FIGMA_ACCESS_DENIED',
  FIGMA_FILE_NOT_FOUND: 'FIGMA_FILE_NOT_FOUND',
  FIGMA_RATE_LIMITED: 'FIGMA_RATE_LIMITED',
  FIGMA_API_ERROR: 'FIGMA_API_ERROR',
  SOURCE_FILE_NOT_CONFIGURED: 'SOURCE_FILE_NOT_CONFIGURED',
  NO_COMPONENTS_FOUND: 'NO_COMPONENTS_FOUND',
  REGISTERED_FILE_NOT_FOUND: 'REGISTERED_FILE_NOT_FOUND',
  SCAN_ALREADY_RUNNING: 'SCAN_ALREADY_RUNNING',
  SCAN_FAILED: 'SCAN_FAILED',
  MAX_RETRY_EXCEEDED: 'MAX_RETRY_EXCEEDED',
  DATABASE_ERROR: 'DATABASE_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  NOT_CONNECTED: 'NOT_CONNECTED',
  FILE_ALREADY_REGISTERED: 'FILE_ALREADY_REGISTERED',
} as const;
